DROP TABLE IF EXISTS ITINERARY;

CREATE TABLE CITY (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(250) NOT NULL
);
 
CREATE TABLE ITINERARY (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  ORIGIN_CITY INT NOT NULL,
  DESTINY_CITY INT NOT NULL,
  DEPARTURE_TIME VARCHAR(250) NOT NULL,
  ARRIVAL_TIME VARCHAR(250) NOT NULL,
  FOREIGN KEY (ORIGIN_CITY) REFERENCES CITY(ID),
  FOREIGN KEY (DESTINY_CITY) REFERENCES CITY(ID)  
);

