DROP TABLE IF EXISTS ITINERARY;
 
CREATE TABLE ITINERARY (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  ORIGIN_CITY VARCHAR(250) NOT NULL,
  DESTINY_CITY VARCHAR(250) NOT NULL,
  DEPARTURE_TIME VARCHAR(250) NOT NULL,
  ARRIVAL_TIME VARCHAR(250) NOT NULL
);